### ISSUE TITLE
Front-end flags from the Java SDK

### ISSUE THREAD

**Issue by sarahlessner** [launchdarkly/java-client#112]
Passing this issue along from a customer:

I'm reading the docs for the Java (https://docs.launchdarkly.com/docs/java-sdk-reference) and JavaScript (https://docs.launchdarkly.com/docs/js-sdk-reference), where it's said I can bootstrap the client-side SDK by providing the FeatureFlags loaded by the back-end.

However, the back-end seems to only have a method like `ldClient.allFlags()`, which loads *all* FeatureFlags, not only those we marked on the UI as front-end ones.

My question is: how can we filter out the FFs so we can print on the page only the flags relevant to the front-end? 
From the `FeatureFlag` class it seems this information is currently only internal?

**Comment by eli-darkly** [comment]
Yes, unfortunately right now that information isn't being sent from the server to the client. It would require a change in the internal API used by the SDKs.

**Comment by scinos** [comment]
Any plans to implement this?

**Comment by eli-darkly** [comment]
@scinos, generally speaking we do plan to implement this, but it's hard for me to be more specific right now because we're in the middle of rolling out some larger changes. I do think it will be a fairly straightforward change, but it's one that has to be made in the LD server as well as the SDKs. There is a major version release of all the SDKs coming up this week, and I'll try to get this scheduled in time for the next minor release of the SDKs after that, assuming I'm right about the relatively small scope of the server-side changes. Sorry this is taking a while - I do understand why not having it is causing difficulties.

**Comment by eli-darkly** [comment]
Sorry, it got put off for quite a while but we're working on it this week.

**Comment by jferrogarcia** [comment]
Any ETA? What version should we look at?

**Comment by eli-darkly** [comment]
There will be a Java SDK 4.3.0 release as soon as we get the necessary changes implemented in the LD application, which we're hoping to do this week.

**Comment by eli-darkly** [comment]
OK, this has been released.

The new method you can use for this is `LDClient.allFlagsState`, which takes a `User` parameter like `allFlags`, plus optional parameters to control its behavior: to get just the client-side flags, you would call `LDClient.allFlagsState(user, FlagsStateOption.CLIENT_SIDE_ONLY)`.

The result is a `FeatureFlagsState` object, rather than a `Map` as you would get from `allFlags`, but if you convert it to JSON with Gson you will still get the appropriate map structure; you can also call `toValuesMap()` to get the equivalent Map.
