### ISSUE TITLE
Can't add custom values of diferent type

### ISSUE THREAD

**Issue by martinblaustein** [launchdarkly/java-client#126]
In launchdarkly app we have a custom rule where a rule can be an int (an id) or a string (a role).

In java it's impossible through the LDUser.Builder to add a List of objects, it only allows a list of String or a list of Number, with the custom, customString and customNumber methods. 

There should be a builder.customObject(String k, List<Object> vs) in order to allow operations that are allowed through js for example.

**Comment by eli-darkly** [comment]
Thanks for pointing this out. It's a reasonable request. One thing I'd change slightly would be to make it take a `List<JsonElement>` rather than a list of `Object`s; while this means that our API is dependent on Gson's classes, that's been our approach elsewhere in the SDK (i.e. in `LDClient.allFlags` and `LDClient.jsonVariation`) when we need to represent an arbitrary value and guarantee that it's a type that can be represented in JSON.

**Comment by martinblaustein** [comment]
> while this means that our API is dependent on Gson's classes
Having that into consideration then I believe it would be a good implementaiton.

Although the `LDClient.allFlags` actually forced us to import gson to be able to process the result, but it's a very generic dependency :)

**Comment by eli-darkly** [comment]
We did basically the same thing for .NET, which is the other strongly-typed platform where we use a third-party JSON library. There's no equivalent in Go, so we just use `interface{}` there even though technically that doesn't guarantee that the value can be marshalled in JSON.

**Comment by eli-darkly** [comment]
Should be fairly soon— I'll try for the first half of this week. It's a very simple change with no effect on the rest of the platform.

**Comment by martinblaustein** [comment]
**AMAZING!**

**Comment by eli-darkly** [comment]
This has been implemented in the 4.1.0 release. :)

**Comment by martinblaustein** [comment]
@eli-darkly Great!
