### ISSUE TITLE
Users Not created unless client connection closed, so does this means do we need to close connection for each request

### ISSUE THREAD

**Issue by prageethw** [launchdarkly/java-client#142]
**user not get created:**
import java.io.IOException;

import com.launchdarkly.client.FeatureFlagsState;
import com.launchdarkly.client.LDClient;
import com.launchdarkly.client.LDUser;

public class FeatureSample {
	private static final String YOUR_SDK_KEY = "sdk-7799b0db-8d76-480b-a072-2073134ed1b3";
	private static LDUser user;
	private static final LDClient ldClient = new LDClient(YOUR_SDK_KEY);

	public static void main(final String[] args) throws IOException {
		long startTime = System.currentTimeMillis();
		user = new LDUser.Builder("default").email("ernestina@example.com").custom("deviceType", "YL0008787782").build();
		validateFetaureFlags(user);
		displayFeatureFlags(user);
		long stopTime = System.currentTimeMillis();
		long elapsedTime = stopTime - startTime;
		System.out.println(elapsedTime);
		//ldClient.close();
	}

	private static void validateFetaureFlags(final LDUser user) {
		boolean showFeature = ldClient.boolVariation("offers", user, false);
		System.out.println(showFeature);
	}

	private static void displayFeatureFlags(final LDUser user) {
		FeatureFlagsState state = ldClient.allFlagsState(user);
		System.out.println(state.toValuesMap().toString());
	}
}

**the user gets created:**
import java.io.IOException;

import com.launchdarkly.client.FeatureFlagsState;
import com.launchdarkly.client.LDClient;
import com.launchdarkly.client.LDUser;

public class FeatureSample {
	private static final String YOUR_SDK_KEY = "sdk-7799b0db-8d76-480b-a072-2073134ed1b3";
	private static LDUser user;
	private static final LDClient ldClient = new LDClient(YOUR_SDK_KEY);

	public static void main(final String[] args) throws IOException {
		long startTime = System.currentTimeMillis();
		user = new LDUser.Builder("default").email("ernestina@example.com").custom("deviceType", "YL0008787782").build();
		validateFetaureFlags(user);
		displayFeatureFlags(user);
		long stopTime = System.currentTimeMillis();
		long elapsedTime = stopTime - startTime;
		System.out.println(elapsedTime);
		ldClient.close();
	}

	private static void validateFetaureFlags(final LDUser user) {
		boolean showFeature = ldClient.boolVariation("offers", user, false);
		System.out.println(showFeature);
	}

	private static void displayFeatureFlags(final LDUser user) {
		FeatureFlagsState state = ldClient.allFlagsState(user);
		System.out.println(state.toValuesMap().toString());
	}
}

**Comment by eli-darkly** [comment]
You definitely do not want to close the connection for each request. There is overhead for creating a client and starting the connection—it's meant to be used for the lifetime of the application.

I think what's going on in your first code example is that your application is terminating before the client has had a chance to send events. Every time you do an evaluation, it generates an event—which among other things tells LaunchDarkly about the user. But in order to make evaluations very fast it does not try to send the event right away; instead they are batched, and processed by a worker thread which periodically flushes them to LaunchDarkly. The time in between flushes is set by the configuration property `flushInterval`, which defaults to 5 seconds. So, if you immediately quit after doing things that take less than 5 seconds, the events aren't delivered and therefore your user isn't recorded.

Events will be delivered sooner than the regular background flushing schedule in two cases:

1. If you call `ldClient.flush()`.
2. If you shut down the client with `ldClient.close()`. You should definitely do this if you are going to exit your application; besides flushing the events, it also causes resources to be released that could otherwise interfere with a clean shutdown. But you shouldn't do it otherwise.

So, in the case of this simple application, `close()` is still appropriate. But in regular usage, while you can use `flush()` to speed up event delivery, it's normally a good idea to just let the event thread do things at its own pace, since batching events can save you some unnecessary HTTP requests.

**Comment by prageethw** [comment]
thanks @eli-darkly  please close this issue, I hope docos could be updated to mention this behavior more precisely, just a suggestion.

**Comment by prageethw** [comment]
@eli-darkly  sorry to dispute above, in my case I don't see flushes happen even after few hrs. The only time it sends events to LD  when it is closed it seems.

**Comment by eli-darkly** [comment]
1. It would be very unusual for there to be no flushes after several hours. How are you determining this? The code you posted won't run for more than a very short time—did you modify it?

2. It is definitely not true that the only time events are sent it when the client is closed. Many applications are constantly running out in the world and sending us events all the time.

3. You don't _need_ to set anything in LDConfig; the defaults will work correctly for most applications. The default event flush interval is five seconds. Your test code is a special case since it terminates almost immediately; there's no way to set a flush interval that is short enough for that, so in that particular case you will need to rely on `close()` to ensure that the events are delivered (which, again, you should do anyway if you are about to exit your application). But in normal usage, for an application that continues running and servicing many requests, the default of five seconds is appropriate.

**Comment by prageethw** [comment]
@eli-darkly yep I got it now, Thanks Please close the defect.

**Comment by eli-darkly** [comment]
Glad it worked out!
